# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# Don't trigger on commits
trigger: none

pr:
  drafts: false
  branches:
    include:
    - release/*
  paths:
    exclude:
    - README.md
    - LICENSE

variables:
  net: '6.x'
  packages: './nuget.config'
  project: '**/Intervip.Razor.csproj'

jobs:
- job: PR_Build
  pool:
    name: Intranet Server

  steps:
  - task: UseDotNet@2
    displayName: 'Download .NET 6.x SDK'
    inputs:
      packageType: 'sdk'
      version: '$(net)'
      performMultiLevelLookup: true
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      projects: '$(project)'
      nugetConfigPath: '$(packages)'
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '$(project)'
      arguments: '--no-restore --configuration release'