# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# Don't trigger on anything
pr: none
trigger: none

# Run o schedule
schedules:
- cron: "0 3 * * *"
  displayName: Nightly Build
  always: true
  branches:
    include:
    - main

variables:
  net: '6.x'
  packages: './nuget.config'
  project: '**/Intervip.Razor.csproj'

jobs:
- job: Nightly_Build
  pool:
    name: Intranet Server

  steps:
  - task: UseDotNet@2
    displayName: 'Download .NET 6.x SDK'
    inputs:
      packageType: 'sdk'
      version: '$(net)'
      performMultiLevelLookup: true
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      projects: '$(project)'
      nugetConfigPath: '$(packages)'
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '$(project)'
      arguments: '--no-restore --configuration release'
  - task: DotNetCoreCLI@2
    displayName: 'Publish'
    inputs:
      command: 'publish'
      projects: '$(project)'
      zipAfterPublish: false
      publishWebProjects: false
      arguments: '--no-restore --configuration release --output $(build.artifactstagingdirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'